baseURL = 'https://mdcooper-mc.github.io'
languageCode = 'en-uk'
title = 'Mark Cooper'
theme = ["github.com/luizdepra/hugo-coder"]
publishDir = "docs"


[params]
author = "Mark Cooper"
info = "Cloud-Native Finance & AI Engineer"
avatarURL = "images/me-toon.png"

# -------------------
#[module]
#[[module.imports]]
#path = "github.com/luizdepra/hugo-coder"

# -------------------

[[params.social]]
name = "Pluralsight"
image = "/images/social/pluralsight.svg"
url = "https://app.pluralsight.com/profile/mark-cooper"
weight = 1
[[params.social]]
name = "Microsoft Azure"
image = "/images/social/azure.svg"
url = "https://www.credly.com/badges/994202cf-a257-4b35-a93b-99e41467072c"
weight = 3
[[params.social]]
icon = "fa-brands fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/m-d-cooper"
weight = 6


# -------------------

[menu]
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 1000
